//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int appointment_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> master_id { get; set; }
        public string client_Familiya { get; set; }
        public string client_name { get; set; }
        public string client_Otchestvo { get; set; }
        public int age { get; set; }
        public int phone_number { get; set; }
    
        public virtual clients clients {  private get; set; }

        public virtual masters masters { private get; set; }
        public virtual services_1 services_1 { private get; set; }
    }
}
