//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA1EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tatuSalonPRAKTIKAEntities : DbContext
    {
        public tatuSalonPRAKTIKAEntities()
            : base("name=tatuSalonPRAKTIKAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointments> appointments { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<masters> masters { get; set; }
        public virtual DbSet<services_1> services_1 { get; set; }
    }
}
